openapi: 3.0.0
info:
  title: HRF Asylum Case API
  description: HRF Asylum API docs
  version: 0.0.12
  
paths: 
  /cases:
   get:
    summary: Gets case data   # Filtering is optional based on query string parameters.
    parameters:
      - name: asylumOffice
        in: query
        description: Asylum Office
        required: false
        schema:
          type: string   # Presents as a comma-delimited list ( e.g. /cases?asylumOffice=zny,zmi,zsf ) to be extracted to an array
      - name: citizenship
        in: query
        description: Citizenship   # This is the origin nation of the asylum petitioner
        required: false
        schema:
          type: string   # Presents as a "0"-delimited list ( e.g. /cases?citizenship=ANGOLA0BELGIUM0FRANCE ) to be extracted to an array    
      - name: caseOutcome
        in: query
        description: Case Outcome   # Three possible outcomes: 'Deny/Referral', 'Grant', or 'Admin Close/Dismissal'
        required: false
        schema:
          type: string
      - name: completionFrom
        in: query
        description: Start date for the Completion search criteria   # The start of the date range for when the asylum petition was decided
        required: false
        schema:
          type: string
      - name: completionTo
        in: query
        description: End date for the Completion search criteria   # The end of the date range for when the asylum petition was decided
        required: false
        schema:
          type: string
      - name: currentDate
        in: query
        description: Current Date   # The date at which information regarding this particular case was deemed "current" (i.e. - when it was added to the data)
        required: false
        schema:
          type: string
      - name: isFiscalYear
        in: query
        description: Fiscal Year   # Boolean setting for which date format to use, calendar year versus fiscal year
        required: false
        schema:
          type: boolean
    responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  "$ref": "#/components/schemas/Case"
        "400":
          description: No cases found for given parameters
          
components:
  schemas:
    Case:
      type: object
      properties:        
        asylumOffice:
          type: string
        citizenship:
          type: string        
        caseOutcome:
          type: string
        completion:
          type: string
        currentDate:
          type: string
